[versions]
spatialBom = "6.0.0"
agp = "8.8.0"
kotlin = "2.0.0"
coreKtx = "1.13.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
androidxLifecycle = "2.10.0"
activityCompose = "1.7.0"
navigationCompose = "2.7.7"
annotation = "1.7.0"
appcompat = "1.6.1"
spotless = "7.0.2"
koin = "3.4.0"

[libraries]
spatial-bom = { module = "com.pico.spatial:bom", version.ref = "spatialBom" }
spatial-foundation = { group = "com.pico.spatial.foundation", name = "foundation" }
spatial-core = { group = "com.pico.spatial.core", name = "core" }
spatial-tracking = { group = "com.pico.spatial.tracking", name = "tracking" }
spatial-sense = { group = "com.pico.spatial.sense", name = "sense" }
spatial-ui-platform = { group = "com.pico.spatial.ui", name = "platform" }
spatial-ui-design = { group = "com.pico.spatial.ui", name = "design" }
spatial-ui-foundation = { group = "com.pico.spatial.ui", name = "foundation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose-android", version.ref = "androidxLifecycle" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
